import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/Components/layout/Navbar";



export const metadata: Metadata = {
  title: "zatiq-clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
