import type { Metadata } from "next"
import "./globals.css"
import { standerd } from "./fonts"
import Navbar from "@/Components/layout/Navbar"
import Footer from "@/Components/layout/Footer"

export const metadata: Metadata = {
  title: "zatiq-clone",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={standerd.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}